In [0]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [0]:
df = pd.read_excel('LG-Data-Nov-22.xlsx')
df.head()

,SUBJECT_ID,Na,GLUCOSE,AGE_AT_LISTING,TREATMENT_PHASE,TX_NUMBER,SEX,RACE,HEIGHT_AT_LISTING,WEIGHT_AT_LISTING,...,ALK_PHOS,PLATELETS,WBC,ALB,EST_GFR,MELD,HGB,INR,listing time,Final State
0,548,140,5.5,49.054795,5,1,1,0,0.0,0.0,...,355,61,3.6,23.0,87,14,116.0,1.3,50,1
1,548,142,5.8,49.054795,5,1,1,0,0.0,0.0,...,316,67,3.8,23.0,85,14,120.0,1.2,50,1
2,548,139,5.2,49.054795,5,1,1,0,0.0,0.0,...,285,58,4.1,22.0,89,16,119.0,1.4,50,1
3,548,139,5.5,49.054795,5,1,1,0,0.0,0.0,...,373,72,3.7,21.0,88,14,119.0,1.3,50,1
4,145,137,7.9,44.298630,4,1,1,0,0.0,0.0,...,152,45,1.9,24.0,114,19,91.0,1.6,49,1

In [0]:
features = ['Na', 'GLUCOSE', 'AGE_AT_LISTING', 'SEX','RACE','HEIGHT_AT_LISTING','WEIGHT_AT_LISTING',
                    'BLOOD_TYPE', 'RH_FACTOR', 'P_DIAG', 'SEC_DIAG', 'SMOKER', 'DIALYSIS_TYPE', 'CREAT', 'BILT', 
                    'AST', 'ALT', 'ALK_PHOS', 'PLATELETS','WBC','ALB','EST_GFR','MELD','HGB','INR','Final State']
newdf = df[features].dropna(axis=0, how='any')

In [0]:
xPatients = newdf.loc[:, newdf.columns!='Final State']
yPatients = df['Final State']
xPatients.head()
print(len(xPatients))

1222

In [0]:
xPatients.head()

,Na,GLUCOSE,AGE_AT_LISTING,SEX,RACE,HEIGHT_AT_LISTING,WEIGHT_AT_LISTING,BLOOD_TYPE,RH_FACTOR,P_DIAG,...,AST,ALT,ALK_PHOS,PLATELETS,WBC,ALB,EST_GFR,MELD,HGB,INR
0,140,5.5,49.054795,1,0,0.0,0.0,4,1,8262,...,92,52,355,61,3.6,23.0,87,14,116.0,1.3
1,142,5.8,49.054795,1,0,0.0,0.0,4,1,8262,...,87,46,316,67,3.8,23.0,85,14,120.0,1.2
2,139,5.2,49.054795,1,0,0.0,0.0,4,1,8262,...,82,50,285,58,4.1,22.0,89,16,119.0,1.4
3,139,5.5,49.054795,1,0,0.0,0.0,4,1,8262,...,85,47,373,72,3.7,21.0,88,14,119.0,1.3
4,137,7.9,44.298630,1,0,0.0,0.0,4,1,8263,...,86,51,152,45,1.9,24.0,114,19,91.0,1.6

In [0]:
xTrain, xTest, yTrain, yTest = train_test_split(xPatients, yPatients, random_state=0, test_size = 0.2)

In [0]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import cross_val_score
from sklearn import metrics
from sklearn.model_selection import GridSearchCV

# Gaussian Classifier
#clf = RandomForestClassifier(n_estimators=100)

#clf.fit(xTrain, yTrain)
#yPredict = clf.predict(xTest)

In [0]:
params_to_search={'n_estimators':[10,50,100,150],
                  'max_depth':[6,8,10,12],
                  'min_samples_split':[2,5,8,10],
                  'min_samples_leaf':[2,5,8,10],
                 }
mdlRF = RandomForestClassifier(criterion='gini',bootstrap=True)
optimized_clf = GridSearchCV(mdlRF,params_to_search,cv=5)
optimized_clf.fit(xTrain,yTrain)

GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators='warn', n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'n_estimators': [10, 50, 100, 150], 'max_depth': [6, 8, 10, 12], 'min_samples_split': [2, 5, 8, 10], 'min_samples_leaf': [2, 5, 8, 10]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [0]:
optimized_clf.best_estimator_

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=8, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=2, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [0]:
score = optimized_clf.best_score_
print(score)

0.9969293756397134

In [0]:
optimized_clf.best_params_

{'max_depth': 8,
 'min_samples_leaf': 2,
 'min_samples_split': 2,
 'n_estimators': 10}

In [0]:
yPred = optimized_clf.predict(xTest)
#scores = cross_val_score(, x_train, y_train, cv=5)
mean_squared_error(yTest, yPred)

0.00816326530612245